updates: logging for cli, fn passing

diff --git a/.nosh/bin/scrawl b/.nosh/bin/scrawl
--- a/.nosh/bin/scrawl
+++ b/.nosh/bin/scrawl
@@ -1,5 +1,5 @@
 #!/usr/bin/env zsh
-#- nlog [level] [event] [message]
+#- scrawl [level] [event] [message]
 #-   Log a message to the console and optionally to a file, based on profile settings.
 
 [[ -z "$Nosh__LogLevel_Console" ]] && export Nosh__LogLevel_Console="info"
@@ -8,7 +8,8 @@ KnownLevels=("trace" "debug" "info" "warn" "error" "fatal")
 Level="debug"
 Message=":shark: :shark: :shark:"
 Event="nosh.event"
-autoload -Uz __log __log_help
+source "$Nosh_LibDir/logging.zsh"
+
 __isEvent() {
   local Event="$1"
   if [[ $Event == *"."* ]]; then
@@ -41,6 +42,10 @@ if [[ $# -eq 0 ]]; then
 else
   Message="$@"
 fi
-
-__log "$Level" "$Event" "$Message"
+if test -t __log >/dev/null; then
+  __log "$Level" "$Event" "$Message"
+else
+ echo "⚧ [$(date "+%Y-%m-%d %H:%M:%S")] [error] nosh.log: Error logging message." 1>&2
+ echo "⚆ [$(date "+%Y-%m-%d %H:%M:%S")] <$Level> |$Event| $Message" 1>&2
+fi
 exit 0
