fix: normal bugs

diff --git a/.nosh/bin/namespaces/util/help b/.nosh/bin/namespaces/util/help
--- a/.nosh/bin/namespaces/util/help
+++ b/.nosh/bin/namespaces/util/help
@@ -18,10 +18,10 @@ Command="$(echo $A[1] | cut -d: -f2)"
 SubCommand="$(echo $A[1] | cut -d: -f3)"
 [[ -z "$Command" ]] && Namespace="$Command" && Command="util"
 Args="${A:2}"
-find -L "$Nosh__BinDir/namespaces" -type d -depth 1 -name "$Namespace" | wc -l | grep -q 1 || echo "Namespace $Namespace not found. Use nosh list to get started." && exit 1
-exec "$Nosh__BinDir/namespaces/sys/arch" &21> /dev/null
+find -L "$Nosh_BinDir/namespaces" -type d -depth 1 -name "$Namespace" | wc -l | grep -q 1 || echo "Namespace $Namespace not found. Use nosh list to get started." && exit 1
+exec "$Nosh_BinDir/namespaces/sys/arch" &21> /dev/null
 # This exported an environment variable
-find -L "$Nosh__BinDir/namespaces/$Namespace" -type f -depth 2 -name "$Command" | wc -l | grep -q 1 || echo "Command $Command not found in namespace $Namespace. Use nosh list to get started." && exit 1
+find -L "$Nosh_BinDir/namespaces/$Namespace" -type f -depth 2 -name "$Command" | wc -l | grep -q 1 || echo "Command $Command not found in namespace $Namespace. Use nosh list to get started." && exit 1
 declare -A CommandInfo
 Current=""
 while read -r Line; do
@@ -29,7 +29,7 @@ while read -r Line; do
   [[ $Line =~ ^#- ]] && CommandInfo["description"]="${Line:3}"
   [[ $Line =~ ^#\s+&(\w+): ]] && CommandInfo["${Line[3,-1]}"]="${Line:5}" && Current="${Line[3,-1]}"
   [[ $Line =~ ^#\s+&\.\.\. ]] && CommandInfo["$Current"]="${CommandInfo["$Current"]}\n${Line:5}"
-done < "$Nosh__BinDir/namespaces/$Namespace/$Command"
+done < "$Nosh_BinDir/namespaces/$Namespace/$Command"
 scrawl info "." "Command: :star4: $Namespace:$Command :star4:"
 for Key in ${(k)CommandInfo}; do
   printf "%-20s %s\n" "$Key" "${CommandInfo[$Key]}"
diff --git a/.nosh/bin/nosh b/.nosh/bin/nosh
--- a/.nosh/bin/nosh
+++ b/.nosh/bin/nosh
@@ -33,20 +33,32 @@ done
 
 Namespace="$(echo $Commands[1] | cut -d: -f1)"
 Command="$(echo $Commands[1] | cut -d: -f2)"
-SubCommand="$(echo $Commands[1] | cut -d: -f3)"
-[[ -z "$Command"]] && Namespace="$Command" && Command="util"
-find -L "$Nosh__BinDir/namespaces" -type d -depth 1 -name "$Namespace" | wc -l | grep -q 1 || echo "Namespace $Namespace not found. Use nosh list to get started." && exit 1
-exec "$Nosh__BinDir/namespaces/sys/arch" &21> /dev/null
-
-# Command can be in the namespace folder or an arch subfolder, 'mac' or 'linux'
-CommandPath="$Nosh__BinDir/namespaces/$Namespace/$Command"
+SubCommand="$(echo $Commands[2])"
+if [[ -z "$Command" ]]; then
+  Command="$Namespace"
+  Namespace="util"
+fi
+  echo "Namespace: $Namespace Command: $Command Subcommand: $Subcommand Remainder: $Remainder" 1>&2
+[[  ! -d "$Nosh_BinDir/namespaces" ]] && scrawl error nosh.namespace "No namespaces found. Use nosh list to get started." && exit 1
+[[ ! -d "$Nosh_BinDir/namespaces/$Namespace" ]] && scrawl error nosh.namespace "Namespace $Namespace not found. Use nosh list to get started." && exit 1
+echo "Namespace found: $Namespace" 1>&2
+# Command can be in the namespace fold r or an arch subfolder, 'mac' or 'linux'
 OSFolder="$(case $(uname -s) in
   Darwin) echo "mac" ;;
   Linux) echo "linux" ;;
   *) echo "general" ;;
 esac)"
-[[ -d "$CommandPath" ]] || CommandPath="$Nosh__BinDir/namespaces/$Namespace/$OSFolder/$Command"
-[[ -d "$CommandPath" ]] || CommandPath="$Nosh__BinDir/namespaces/$Namespace/$(uname -s)/$Command"
-[[ -d "$CommandPath" ]] || scrawl error nosh.command "Command $Command not found in namespace $Namespace" && exit 1
-exec "$CommandPath" $Subcommand "$Remainder"
+echo "OSFolder: $OSFolder" 1>&2
+CorePath="$Nosh_BinDir/namespaces/$Namespace"
+if [[ -x "$CorePath/$Command" ]]; then
+  CommandPath="$CorePath/$Command"
+elif [[ -x "$CorePath/$OSFolder/$Command" ]]; then
+  CommandPath="$CorePath/$OSFolder/$Command"
+elif [[ -f "$CorePath/$OSFolder/util/$Command" ]]; then
+  CommandPath="$CorePath/$OSFolder/util/$Command"
+else
+  scrawl error nosh.command "Command $Command not found in namespace $Namespace" && exit 1
+fi
+echo "Running command: $CommandPath $Subcommand $Remainder" 1>&2
+exec "$CommandPath" "$Subcommand" "$Remainder"
 exit 0
