fix: nosh list

diff --git a/.nosh/bin/namespaces/util/list b/.nosh/bin/namespaces/util/list
--- a/.nosh/bin/namespaces/util/list
+++ b/.nosh/bin/namespaces/util/list
@@ -1,18 +1,23 @@
 #!/usr/bin/env zsh
 #- nosh [util:]list [namespace] - list all available commands.
-echo "$1 $2 $3 $4 $5" 1>&2
-[[ -z "$2" ]] &&
-Namespace="$2"
+[[ -z "$2" ]] && Namespace="$2"
 [[ -z "$Namespace" ]] && Namespace="util"
-
-Files=("$(find -L "$Nosh_BinDir/namespaces/$Namespace" -type f -name "*" | cut -d/ -f6 | cut -d. -f1 | sort)")
-for File in $Files; do
-  echo "$File" 1>&2
-  Description="$(head -n5 "$Nosh_BinDir/namespaces/$Namespace/$File" | grep "#- " | cut -c4-)"
-  # lpad filename. If it is in an arch subfolder, move it so mac/file -> file (mac)
-  [[ $File == *"/"* ]] && File="$(echo $File | cut -d/ -f2) ($(echo $File | cut -d/ -f1))"
-  printf "%-20s %s\n" "$File" "$Description"
+[[ -z "$LC_ALL" ]] && export LC_ALL="C"
+[[ -z "$LANG" ]] && LANG="en"
+[[ -z "$LC_TERMINAL" ]] && LC_TERMINAL="tty"
+echo "Searching $Nosh_BinDir/namespaces/$Namespace" 1>&2
+[[ ! -d "$Nosh_BinDir/namespaces/$Namespace" ]] && scrawl error nosh.namespace "Namespace $Namespace not found. Use nosh util:list to get started." && exit 1
+Files=($(find -L "$Nosh_BinDir/namespaces/$Namespace" -type f -name "*" | sort) )
+# iterate through files in the namespace folder
+for F in "${Files[@]}"; do
+  # Get the first 10 lines of the file, find the first line that starts with #-, and cut off the first 3 characters
+  Description="$(head -n10 "$F" | grep "^#- " | cut -c3-)"
+  # Remove all folders from the path in F, up to the folder matching namespaces/\w+/
+  F="$(echo "$F" | perl -pe "s/.+\/(\w+)/\1/")"
+  # If the file is in the root of the namespace, it is a mac/linux file, so just print it.
+  # If it is in a subfolder, print it as mac/file -> file (mac)
+  printf "%-20s %-40s\n" "$F" "$Description" 1>&2
 done
-echo "\n\nMore namespaces: ${$(ls -1 "$Nosh_BinDir/namespaces" | tr '\n' '|')}" &1>2
-echo "For more info on one command, run nosh util:help [namespace] [command]" &1>2
+#echo "\n\nMore namespaces: ${$(ls -1 "$Nosh_BinDir/namespaces" | tr '\n' '|')}" &1>2
+#echo "For more info on one command, run nosh util:help [namespace] [command]" &1>2
 exit 0
diff --git a/.nosh/bin/nosh b/.nosh/bin/nosh
--- a/.nosh/bin/nosh
+++ b/.nosh/bin/nosh
@@ -50,25 +50,23 @@ if [[ -z "$Command" ]]; then
   Command="$Namespace"
   Namespace="util"
 fi
-  echo "Namespace: $Namespace Command: $Command Subcommand: $Subcommand Remainder: $Remainder" 1>&2
-[[  ! -d "$Nosh_BinDir/namespaces" ]] && scrawl error nosh.namespace "No namespaces found. Use nosh list to get started." && exit 1
-[[ ! -d "$Nosh_BinDir/namespaces/$Namespace" ]] && scrawl error nosh.namespace "Namespace $Namespace not found. Use nosh list to get started." && exit 1
-# Command can be in the namespace fold r or an arch subfolder, 'mac' or 'linux'
+
+RemainderTitle=$([[ -z "$Remainder" ]] && echo "" || echo "Arguments: $Remainder")
+  echo "Namespace: $Namespace Command: $Command Subcommand: $Subcommand $RemainderTitle" 1>&2
+[[  ! -d "$Nosh_BinDir/namespaces" ]] && scrawl error nosh.namespace "No namespaces found! Do you need to update your nosh install?" && exit 1
+[[ ! -d "$Nosh_BinDir/namespaces/$Namespace" ]] && scrawl error nosh.namespace "Namespace $Namespace not found. Use nosh util:list to get started." && exit 1
+# Command can be in the namespace folder or an arch subfolder, 'mac' or 'linux'
 OSFolder="$(case $(uname -s) in
   Darwin) echo "mac" ;;
   Linux) echo "linux" ;;
   *) echo "general" ;;
 esac)"
 CorePath="$Nosh_BinDir/namespaces/$Namespace"
-if [[ -x "$CorePath/$Command" ]]; then
-  CommandPath="$CorePath/$Command"
-elif [[ -x "$CorePath/$OSFolder/$Command" ]]; then
-  CommandPath="$CorePath/$OSFolder/$Command"
-elif [[ -f "$CorePath/$OSFolder/util/$Command" ]]; then
-  CommandPath="$CorePath/$OSFolder/util/$Command"
-else
-  scrawl error nosh.command "Command $Command not found in namespace $Namespace" && exit 1
-fi
-echo "Running command: $(basename "$CommandPath")  \"$Subcommand\"   \"${Remainder}\"" 1>&2
+CommandPath=""
+[[ -x "$CorePath/$Command" ]] && CommandPath="$CorePath/$Command"
+[[ -x "$CorePath/$OSFolder/$Command" ]] && CommandPath="$CorePath/$OSFolder/$Command"
+[[ -f "$CorePath/$OSFolder/util/$Command" ]] && CommandPath="$CorePath/$OSFolder/util/$Command"
+[[ -z "$CommandPath" ]] && scrawl error nosh.command "Command $Command not found in namespace $Namespace" && exit 1
+echo "Running command: $(basename "$CommandPath") \"$Subcommand\" \"${Remainder}\"" 1>&2
 $($CommandPath "$Subcommand" "${Remainder[@]}")
 exit 0
