chore: add a personal app with a menu bar

diff --git a/.nosh/bin/namespaces/app/sass b/.nosh/bin/namespaces/app/sass
--- a/.nosh/bin/namespaces/app/sass
+++ b/.nosh/bin/namespaces/app/sass
@@ -2,8 +2,26 @@
 #- nosh app:sass - compile sass files to css for all apps
 # &usage: nosh app:sass [app]
 
-# &description: nosh app:sass compiles sass files to css for all apps in the monorepo.E
-[[ -x "$(bun run which sass 2>/dev/null)" ]] || nosh sanity:sass
-[[ -x "$(bun run which sass 2>/dev/null)" ]] || scrawl error sass.preinstall "Terminated early - sass missing." && exit 1
-find app -maxdepth 1 -type d -regex "app.[a-z]*" -exec bun run sass {} \;
-exit 0
+# &description: nosh app:sass compiles sass files to css for all apps in the monorepo.
+
+# is sass installed globally?
+if [[ ! -z "$(sass 2>/dev/null)" ]]; then
+  find app -maxdepth 1 -type d -regex "app.[a-z]*" -exec sass {} \;
+  exit 0
+fi
+
+# is sass installed locally?
+if [[ -x "$(bun run which sass 2>/dev/null)" ]]; then
+  find app -maxdepth 1 -type d -regex "app.[a-z]*" -exec bun run sass {} \;
+  exit 0
+fi
+
+# install sass
+scrawl info sass.install "Sass not found. Installing."
+nosh sanity:sass
+if [[ -x "$(bun run which sass 2>/dev/null)" ]]; then
+  find app -maxdepth 1 -type d -regex "app.[a-z]*" -exec bun run sass {} \;
+  exit 0
+fi
+scrawl error sass.install "Could not find sass! Please install it manually."
+exit 1
